### ISSUE TITLE
登录时报错登陆状态已失效

### ISSUE THREAD

**Issue by FollowHeart-Lu** [amerainc/rainc-job#2]
大佬，我在电脑上跑您的项目，前后端正常运行起来，也建立了空的数据库，登陆总是说没有登录或登录已失效。这是什么原因啊

**Comment by FollowHeart-Lu** [comment]
> 大佬，我在电脑上跑您的项目，前后端正常运行起来，也建立了空的数据库，登陆总是说没有登录或登录已失效。这是什么原因啊
报错是402

**Comment by amerainc** [comment]
你好已经修复了，刚毕业的时候做前端单点登录测试把测试代码给不小心带进去了
